### ISSUE TITLE
Add block ID Name support

### ISSUE THREAD

**Issue by Khroki** [Khroki/MCEdit-Unified#590]
While items are already converted over, some kind of system for handling the new name id system should probably be looked into. Now currently blocks contain both ID data and ID Name and their subtypes (Such as powered:true and variant:cobble). Thinking about it we don't really need to interfere with the numerical system, we just need to make it load and save the ID names in addition to the numerical data. 

This would require a method to retrieve the block ID names from NBT if the numerical ID can't be found, then using the block definition YAML figure out what ID the block belongs to. (This will require significant additions to minecraft.yaml). After that you now have both the ID and ID Name, regardless of if mcedit loaded via ID or ID Name. 

An example, MCEdit wants to load a Lever in a build that doesn't support numerical IDs:
MCEdit first checks for numerical ID as usual, upon failure retrieves 'minecraft:lever facing:east powered:true' from NBT and looks in the yaml for an entry containing:

```
  idName: minecraft:lever
  var1:facing:east
  var2:powered:true
```

which returns ID 69:9, mcedit loads the block but has both ID and ID name now. After the normal editing, this data in the yaml is then resaved into NBT. The lever entry would look something like   

```
- id: 69
    idStr: lever
    idName: minecraft:lever
    name: Lever
    mapcolor: [124, 98, 62]
    tex: [0, 6]
    type: LEVER
    tex_extra:
      base: [0, 1]
    opacity: 0
    data:
[data removed for brevity]
      9:
        name: Lever (Powered, East)
        var1: facing:east
        var2: powered:true
      10:
```

Have it look for the same number of variables the block contains, as some have way more than others.

In a world that does support both, such as 1.8, simply load the ID and ID name. If ID names are missing simply ignore them., if numerical IDs are missing hash the ID name and subtype data to generate a numerical ID and damage value that will be the same for all users with that block. Make this number somewhat large, like over 10000 and disallow mcedit from saving numbers over this arbitrary minimum when writing NBT so only the ID name is saved to the world, but you can still use it for schematics. It would need to be something like hash+10000 to prevent numbers like 0041:0004 from being generated. (becoming 10041:0004)

Editing can now proceed as normal using numerical IDs, with the ID names and numerical IDs being displayed in tooltips. When finished, save both the ID and ID name data retrieved earlier to NBT and it should be fully functional, no lookups when saving. Schematic functionality may not have to change under this system but an expansion of it couldn't hurt.

Thoughts?
