### ISSUE TITLE
Wrong saving of lightmap [mods]

### ISSUE THREAD

**Issue by Dushess** [Khroki/MCEdit-Unified#594]
Maybe not an issue, but the problem:
MCEdit has flag -light source- only for glowstone, that's correct, i have some mods that contain another light sources (tile.projectred.illumination.lamp, pr_fixture(mini-lamp) from ProjectRed too and fluorescent from RealTrainsMod). After some building procedures in my map(new light sources affected) with few relight uses in editor i got strange things. Near that items game save lights, like here's glowstone and it appears everytime, when i cover this by solid block new center of lighting can appear nearby in coverage area of first that sourse. This continues until i cover some part of first instance of this light area.
I think the reason is that situation: editor don't knows that described blocks is light sourse too, i can understand it, but why that problem appears after relight procedure? MCEdit saves area as non-glowing, right? Can we do sometning?

p.s. not have that problem with RTM, his lamps just light source only ingame, albeit after fixing i still have some small shadowed strips ih his location, it can be suppressed by other lamps. 
And yes, here screenshot, how it looks.
![2016-03-01_20 22 45](https://cloud.githubusercontent.com/assets/15954961/13437517/17fec55e-dffe-11e5-847a-0938ef42eba1.png)

Will ask, exist ways to mark needed blocks as light source for correct lightmap saving? Oh, i forgot, ProjectRed lamps is redstone powered, it seems thats not unchangeable lightsourse like glowstone
_Huh, sorry for wall of text, this really annoying._

**Comment by Khroki** [comment]
This is because unless a block is defined in the YAML it has no way of knowing any of it's attributes. Only way around this atm is to create custom minecraft.yaml entries since that's what it uses for lighting and transparency. MCEdit only relights chunks that were modified.

**Comment by Dushess** [comment]
That's strange, becouse this chunks was modified many times before.

**Comment by Khroki** [comment]
did you change any lighting before?

**Comment by Dushess** [comment]
Yes

**Comment by Khroki** [comment]
Well, regardless of previous behavior mcedit won't light mod blocks unless they have an entry.

**Comment by Dushess** [comment]
Ok, hmmm, how would then reset lightmap to its original state?

**Comment by Khroki** [comment]
you'd have to restore from a backup or undo if your edit session is still open. I don't believe we have a function for not relighting on save.

**Comment by Dushess** [comment]
Nonono, thats exist even not today

**Comment by Khroki** [comment]
Thing is we don't really support mods since we have no good way of handling entries, especially since IDs aren't fixed like regular MC, and mcedit relies pretty heavily on fixed IDs.

**Comment by Khroki** [comment]
what?

**Comment by Dushess** [comment]
Hm, and how about client sided? I mean make not strong link to block id and set block to light source for current session, after saving it will be normal light, like all the same glowstone.

**Comment by Khroki** [comment]
Only way to make mcedit relight properly would be for you to find the block IDs of all modded lights and make entries in the yaml for them all including their brightness level (Glowstone is 15, torches I think 14 etc.) You can do this client side via mcedit/pymclevel/minecraft.yaml but make sure to use spaces and not tabs.

**Comment by Khroki** [comment]
We want to eventually augment the ID system to support block ID names, but that is in limbo for now. Either way a yaml entry would be required.

**Comment by Dushess** [comment]
Ok

**Comment by Khroki** [comment]
Just copy the glowstone entry, rename it, change the id and it should work.

**Comment by Dushess** [comment]
Thanks

**Comment by Khroki** [comment]
Note when you update mcedit this entry will be wiped, so if it works make a backup of the file.

**Comment by Dushess** [comment]
region updating?

**Comment by Dushess** [comment]
So, i look into configs, here's a little problem: PR lamps is multicolor, but his class still -redstone lamp-
I can use this template, but redstone lamp has no colors, need somehow attach this...

**Comment by Khroki** [comment]
What class are you talking about? MCEdit's system doesn't use classes. Also mcedit only supports vanilla style lighting.

**Comment by Dushess** [comment]
class is hypotetically, just lamp, powered on redstone used for tile.projectred.illumination.lamp

**Comment by Khroki** [comment]
oh you want it to only light the powered ones, then you have to define each damage value seperately, like so:
```
  - id: 89
    idStr: Lamp
    name: RedLamp
    mapcolor: [249, 212, 156]
    tex: [0, 0]
    data:
      8:
        brightness: 15
      9:
        brightness: 15
      10:
        brightness: 15
      11:
        brightness: 15
      12:
        brightness: 15
      13:
        brightness: 15
      14:
        brightness: 15
  ```
Any damage values not specified inherit from the base entry. As you can see this setup overrides brightness on the damage values listed.

**Comment by Dushess** [comment]
Ok, like that
Will be better
 
```
  - id: 35
    idStr: wool
    name: White Wool
    mapcolor: [222, 222, 222]
    tex: [0, 4]
    data:
      0:
        tex: [0, 4]
        name: Wool (White)
        mapcolor: [222, 222, 222]
      1:
        tex: [2, 13]
        name: Orange Wool
        mapcolor: [234, 127, 55]
      2:
        tex: [2, 12]
        name: Magenta Wool
        mapcolor: [191, 75, 201]
      3:
        tex: [2, 11]
        name: Light Blue Wool
        mapcolor: [104, 139, 212]
      4:
        tex: [2, 10]
        name: Yellow Wool
        mapcolor: [104, 139, 212]
      5:
        tex: [2, 9]
        name: Lime Wool
        mapcolor: [59, 189, 48]
      6:
        tex: [2, 8]
        name: Pink Wool
        mapcolor: [217, 131, 155]
      7:
        tex: [2, 7]
        name: Gray Wool
        search: grey
        mapcolor: [66, 66, 66]
      8:
        tex: [1, 14]
        name: Light Gray Wool
        search: grey
        mapcolor: [166, 166, 166]
      9:
        tex: [1, 13]
        name: Cyan Wool
        mapcolor: [39, 117, 149]
      10:
        tex: [1, 12]
        name: Purple Wool
        mapcolor: [129, 54, 196]
      11:
        tex: [1, 11]
        name: Blue Wool
        mapcolor: [39, 51, 161]
      12:
        tex: [1, 10]
        name: Brown Wool
        mapcolor: [86, 51, 28]
      13:
        tex: [1, 9]
        name: Green Wool
        mapcolor: [56, 77, 24]
      14:
        tex: [1, 8]
        name: Red Wool
        mapcolor: [164, 45, 41]
      15:
        tex: [1, 7]
        name: Black Wool
        mapcolor: [0, 0, 0]
```
